# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createTextFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createTextFile(object):
    def setupUi(self, createTextFile):
        createTextFile.setObjectName("createTextFile")
        createTextFile.resize(325, 204)
        self.centralwidget = QtWidgets.QWidget(createTextFile)
        self.centralwidget.setObjectName("centralwidget")
        self.newTextFileName = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.newTextFileName.setGeometry(QtCore.QRect(80, 60, 161, 31))
        self.newTextFileName.setObjectName("newTextFileName")
        self.createFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.createFileBtn.setGeometry(QtCore.QRect(110, 120, 93, 28))
        self.createFileBtn.setObjectName("createFileBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        createTextFile.setCentralWidget(self.centralwidget)

        self.retranslateUi(createTextFile)
        QtCore.QMetaObject.connectSlotsByName(createTextFile)

    def retranslateUi(self, createTextFile):
        _translate = QtCore.QCoreApplication.translate
        createTextFile.setWindowTitle(_translate("createTextFile", "MainWindow"))
        self.createFileBtn.setText(_translate("createTextFile", "Create"))
        self.label.setText(_translate("createTextFile", "Enter New File Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createTextFile = QtWidgets.QMainWindow()
    ui = Ui_createTextFile()
    ui.setupUi(createTextFile)
    createTextFile.show()
    sys.exit(app.exec_())
