# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fileSelector(object):
    def setupUi(self, fileSelector):
        fileSelector.setObjectName("fileSelector")
        fileSelector.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fileSelector.sizePolicy().hasHeightForWidth())
        fileSelector.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(fileSelector)
        self.centralwidget.setObjectName("centralwidget")
        self.newFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newFileBtn.setGeometry(QtCore.QRect(680, 550, 93, 28))
        self.newFileBtn.setAutoDefault(False)
        self.newFileBtn.setObjectName("newFileBtn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 751, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.filesGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.filesGrid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.filesGrid.setContentsMargins(0, 0, 0, 0)
        self.filesGrid.setObjectName("filesGrid")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        fileSelector.setCentralWidget(self.centralwidget)
        self.actionNew = QtWidgets.QAction(fileSelector)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_file = QtWidgets.QAction(fileSelector)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionDelete_file = QtWidgets.QAction(fileSelector)
        self.actionDelete_file.setObjectName("actionDelete_file")

        self.retranslateUi(fileSelector)
        QtCore.QMetaObject.connectSlotsByName(fileSelector)

    def retranslateUi(self, fileSelector):
        _translate = QtCore.QCoreApplication.translate
        fileSelector.setWindowTitle(_translate("fileSelector", "File selector"))
        self.newFileBtn.setText(_translate("fileSelector", "New File"))
        self.label.setText(_translate("fileSelector", "Files:"))
        self.actionNew.setText(_translate("fileSelector", "New file"))
        self.actionOpen_file.setText(_translate("fileSelector", "Open file"))
        self.actionDelete_file.setText(_translate("fileSelector", "Delete file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fileSelector = QtWidgets.QMainWindow()
    ui = Ui_fileSelector()
    ui.setupUi(fileSelector)
    fileSelector.show()
    sys.exit(app.exec_())
